export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_ITEM = 'add_item'
export const Login_NAME = 'login_name'
export const Login_PWD = 'login_pwd'
export const Login = 'login'
export const Sign = 'Sign'
//export const Login_isAuth_F = 'login_isAuth_false'
//export const Login_isAuth_T = 'login_isAuth_true'

export const Register_NAME = 'register_name'
export const Register_PWD = 'register_pwd'
export const Register_sPWD = 'register_spwd'
export const Register_Npassword = 'register_npassword'
export const Register = 'register'